version: '3.9'

services:
  wikdpstp03:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    expose:
      - "8081"
    deploy:
      replicas: 4
    restart: always
    environment:
      - PING_LISTEN_PORT=8081
    networks:
      - front-network

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - wikdpstp03
    networks:
      - front-network

networks:
  front-network:
    driver: bridge

volumes:
  db_data: